/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class power_ConsoleSize */

#ifndef _Included_power_ConsoleSize
#define _Included_power_ConsoleSize
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     power_ConsoleSize
 * Method:    initialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_power_ConsoleSize_initialize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
