/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class power_Console */

#ifndef _Included_power_Console
#define _Included_power_Console
#ifdef __cplusplus
extern "C" {
#endif
#undef power_Console_BLUE
#define power_Console_BLUE 1L
#undef power_Console_GREEN
#define power_Console_GREEN 2L
#undef power_Console_RED
#define power_Console_RED 4L
#undef power_Console_BRIGHT
#define power_Console_BRIGHT 8L
/*
 * Class:     power_Console
 * Method:    readNoEcho
 * Signature: ()C
 */
JNIEXPORT jchar JNICALL Java_power_Console_readNoEcho
  (JNIEnv *, jclass);

/*
 * Class:     power_Console
 * Method:    write
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_power_Console_write
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
