/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class AWTChildCompTest */

#ifndef _Included_AWTChildCompTest
#define _Included_AWTChildCompTest
#ifdef __cplusplus
extern "C" {
#endif
#undef AWTChildCompTest_FOCUS_TRAVERSABLE_UNKNOWN
#define AWTChildCompTest_FOCUS_TRAVERSABLE_UNKNOWN 0L
#undef AWTChildCompTest_FOCUS_TRAVERSABLE_DEFAULT
#define AWTChildCompTest_FOCUS_TRAVERSABLE_DEFAULT 1L
#undef AWTChildCompTest_FOCUS_TRAVERSABLE_SET
#define AWTChildCompTest_FOCUS_TRAVERSABLE_SET 2L
#undef AWTChildCompTest_TOP_ALIGNMENT
#define AWTChildCompTest_TOP_ALIGNMENT 0.0f
#undef AWTChildCompTest_CENTER_ALIGNMENT
#define AWTChildCompTest_CENTER_ALIGNMENT 0.5f
#undef AWTChildCompTest_BOTTOM_ALIGNMENT
#define AWTChildCompTest_BOTTOM_ALIGNMENT 1.0f
#undef AWTChildCompTest_LEFT_ALIGNMENT
#define AWTChildCompTest_LEFT_ALIGNMENT 0.0f
#undef AWTChildCompTest_RIGHT_ALIGNMENT
#define AWTChildCompTest_RIGHT_ALIGNMENT 1.0f
#undef AWTChildCompTest_serialVersionUID
#define AWTChildCompTest_serialVersionUID -7644114512714619750i64
#undef AWTChildCompTest_serialVersionUID
#define AWTChildCompTest_serialVersionUID 4613797578919906343i64
#undef AWTChildCompTest_INCLUDE_SELF
#define AWTChildCompTest_INCLUDE_SELF 1L
#undef AWTChildCompTest_SEARCH_HEAVYWEIGHTS
#define AWTChildCompTest_SEARCH_HEAVYWEIGHTS 1L
#undef AWTChildCompTest_OPENED
#define AWTChildCompTest_OPENED 1L
#undef AWTChildCompTest_serialVersionUID
#define AWTChildCompTest_serialVersionUID 4497834738069338734i64
#undef AWTChildCompTest_DEFAULT_CURSOR
#define AWTChildCompTest_DEFAULT_CURSOR 0L
#undef AWTChildCompTest_CROSSHAIR_CURSOR
#define AWTChildCompTest_CROSSHAIR_CURSOR 1L
#undef AWTChildCompTest_TEXT_CURSOR
#define AWTChildCompTest_TEXT_CURSOR 2L
#undef AWTChildCompTest_WAIT_CURSOR
#define AWTChildCompTest_WAIT_CURSOR 3L
#undef AWTChildCompTest_SW_RESIZE_CURSOR
#define AWTChildCompTest_SW_RESIZE_CURSOR 4L
#undef AWTChildCompTest_SE_RESIZE_CURSOR
#define AWTChildCompTest_SE_RESIZE_CURSOR 5L
#undef AWTChildCompTest_NW_RESIZE_CURSOR
#define AWTChildCompTest_NW_RESIZE_CURSOR 6L
#undef AWTChildCompTest_NE_RESIZE_CURSOR
#define AWTChildCompTest_NE_RESIZE_CURSOR 7L
#undef AWTChildCompTest_N_RESIZE_CURSOR
#define AWTChildCompTest_N_RESIZE_CURSOR 8L
#undef AWTChildCompTest_S_RESIZE_CURSOR
#define AWTChildCompTest_S_RESIZE_CURSOR 9L
#undef AWTChildCompTest_W_RESIZE_CURSOR
#define AWTChildCompTest_W_RESIZE_CURSOR 10L
#undef AWTChildCompTest_E_RESIZE_CURSOR
#define AWTChildCompTest_E_RESIZE_CURSOR 11L
#undef AWTChildCompTest_HAND_CURSOR
#define AWTChildCompTest_HAND_CURSOR 12L
#undef AWTChildCompTest_MOVE_CURSOR
#define AWTChildCompTest_MOVE_CURSOR 13L
#undef AWTChildCompTest_NORMAL
#define AWTChildCompTest_NORMAL 0L
#undef AWTChildCompTest_ICONIFIED
#define AWTChildCompTest_ICONIFIED 1L
#undef AWTChildCompTest_MAXIMIZED_HORIZ
#define AWTChildCompTest_MAXIMIZED_HORIZ 2L
#undef AWTChildCompTest_MAXIMIZED_VERT
#define AWTChildCompTest_MAXIMIZED_VERT 4L
#undef AWTChildCompTest_MAXIMIZED_BOTH
#define AWTChildCompTest_MAXIMIZED_BOTH 6L
#undef AWTChildCompTest_serialVersionUID
#define AWTChildCompTest_serialVersionUID 2673458971256075116i64
/*
 * Class:     AWTChildCompTest
 * Method:    flash
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_AWTChildCompTest_flash
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
