/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeConsole */

#ifndef _Included_NativeConsole
#define _Included_NativeConsole
#ifdef __cplusplus
extern "C" {
#endif
#undef NativeConsole_BLUE
#define NativeConsole_BLUE 1L
#undef NativeConsole_GREEN
#define NativeConsole_GREEN 2L
#undef NativeConsole_RED
#define NativeConsole_RED 4L
#undef NativeConsole_BRIGHT
#define NativeConsole_BRIGHT 8L
/*
 * Class:     NativeConsole
 * Method:    print
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_NativeConsole_print
  (JNIEnv *, jclass, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
